###################################################################
# Michael Hayworth
# 3/9/2022
###################################################################
# Makefile
# Eases the compilation of the program
###################################################################

twosum : two_sum.cpp
	g++ two_sum.cpp -o twosum

clean :
	rm -f twosum