###################################################################
# Michael Hayworth
# 3/11/2022
###################################################################
# Makefile
# Eases the compilation of the program
###################################################################

median : median.cpp
	g++ median.cpp -o median

clean :
	rm -f median