###################################################################
# Michael Hayworth
# 3/10/2022
###################################################################
# Makefile
# Eases the compilation of the program
###################################################################

addtwonums : add_two_nums.cpp
	g++ add_two_nums.cpp -o addtwonums

clean :
	rm -f addtwonums