###################################################################
# Michael Hayworth
# 3/10/2022
###################################################################
# Makefile
# Eases the compilation of the program
###################################################################

longestsubstr : longest_substr.cpp
	g++ longest_substr.cpp -o longestsubstr

clean :
	rm -f longestsubstr